Add dynamic viscosity quantity with related units and tests
iliekturtles/uom pull request #323
Opened 2022-08-03 09:31 UTC by crystal-growth

Dynamic viscosity quantity [Pressure x Time] with derived and imperial units.

2022-08-10 15:11 UTC, crystal-growth commented
Rebased to current master, fixing merge conflict in mod.rs.

2022-08-12 00:44 UTC, iliekturtles requested changes

2022-08-12 00:44 UTC, iliekturtles commented on src/si/dynamic_viscosity.rs
> +    /// Dimension of dynamic viscosity, ML⁻¹T⁻¹ (base unit pascal second, kg · m⁻¹ · s⁻¹).
Dimensions in ISQ order.

```suggestion
    /// Dimension of dynamic viscosity, L⁻¹MT⁻¹ (base unit pascal second, kg · m⁻¹ · s⁻¹).
```

2022-08-12 00:44 UTC, iliekturtles commented on src/si/dynamic_viscosity.rs
> +            "gram per centimeter second", "grams per centimeter second";
* Formatting
 * In my brief searching I couldn't find any reference about `poises` being the plural of `poise` and `reyn` of `reyn`. Will you verify?

```suggestion
        @pascal_second: prefix!(none); "Pa · s", "pascal second", "pascal seconds";
        @millipascal_second: prefix!(milli); "mPa · s", "millipascal second", "millipascal seconds";
        @micropascal_second: prefix!(micro); "µPa · s", "micropascal second", "micropascal seconds";
        // poise = 0.1 Pa · s
        @poise: 1.0_E-1; "P", "poise", "poises";
        // centipoise = 1 mPa · s
        @centipoise: prefix!(centi) * 1.0_E-1; "cP", "centipoise", "centipoises";
        @pound_force_second_per_square_foot: 4.448_222_E0 / 3.048_E-1 / 3.048_E-1; "lbf · s/ft²",
            "pound-force second per square foot", "pound-force seconds per square foot";
        @pound_force_second_per_square_inch: 4.448_222_E0 / 2.54_E-2 / 2.54_E-2; "lbf · s/in²",
            "pound-force second per square inch", "pound-force seconds per square inch";
        // Reyn = 1 lbf · s/in²
        @reyn: 4.448_222_E0 / 2.54_E-2 / 2.54_E-2; "reyn", "reyn", "reyn";
        @pound_per_foot_second: 4.535_924_E-1 / 3.048_E-1; "lb/(ft · s)", "pound per foot second",
            "pounds per foot second";
        @pound_per_foot_hour: 4.535_924_E-1 / 3.048_E-1 / 3.6_E3; "lb/(ft · h)",
            "pound per foot hour", "pounds per foot hour";
        @slug_per_foot_second: 1.459_390_E1 / 3.048_E-1; "slug/(ft · s)", "slug per foot second",
            "slugs per foot second";
        @gram_per_centimeter_second: prefix!(milli) / prefix!(centi); "g/(cm · s)",
            "gram per centimeter second", "grams per centimeter second";
```

2022-08-12 00:44 UTC, iliekturtles commented on src/si/dynamic_viscosity.rs
> +            test::<dv::pascal_second, t::second, p::pascal>();
I'd like to see the generic parameters in formula order: pressure * time = dynamic viscosity.

```suggestion
            test::<p::pascal, t::second, dv::pascal_second>();
```

2022-08-12 00:44 UTC, iliekturtles commented on src/si/dynamic_viscosity.rs
> +            test::<dv::pound_force_second_per_square_inch, t::second, p::pound_force_per_square_inch>();
Wrap long lines.

```suggestion
            test::<dv::pound_force_second_per_square_foot, t::second,
                p::pound_force_per_square_foot>();
            test::<dv::pound_force_second_per_square_inch, t::second,
                p::pound_force_per_square_inch>();
```

2022-08-12 00:44 UTC, iliekturtles commented on src/si/dynamic_viscosity.rs
> +
```suggestion
        }
```

2022-08-12 00:44 UTC, iliekturtles commented on src/si/dynamic_viscosity.rs
> +            test::<dv::pound_per_foot_second, t::second, m::pound, l::foot>();
Generic parameters in formula order again.

```suggestion
            test::<m::pound, l::foot, t::second, dv::pound_per_foot_second>();
```

2022-08-12 00:44 UTC, iliekturtles commented on src/si/dynamic_viscosity.rs
> +            fn test<DV: dv::Conversion<V>, T: t::Conversion<V>, M: m::Conversion<V>, L: l::Conversion<V>>() {
Wrap long line.

```suggestion
            fn test<DV: dv::Conversion<V>, T: t::Conversion<V>, M: m::Conversion<V>,
                L: l::Conversion<V>>()
            {
```

or

```suggestion
            fn test<
                DV: dv::Conversion<V>,
                T: t::Conversion<V>,
                M: m::Conversion<V>,
                L: l::Conversion<V>>()
            {
```

2022-08-12 07:22 UTC, crystal-growth commented
I'm not sure about plurals for Poise
"Poises" is frequently used, especially in older literature:
https://ceramics.onlinelibrary.wiley.com/doi/abs/10.1111/j.1151-2916.1963.tb11684.x
https://www.sciencedirect.com/science/article/pii/001910359190090G
Same for reyn: 
"Reyns" are used in older texts: https://ntrs.nasa.gov/api/citations/19930083501/downloads/19930083501.pdf

The newer texts use standard SI units or abbreviations

2022-08-15 19:14 UTC, iliekturtles requested changes
Just some minor formatting then I think we're ready to merge!

2022-08-15 19:14 UTC, iliekturtles commented on src/si/dynamic_viscosity.rs
> +            test::<p::micropascal,  t::second, dv::micropascal_second>();
```suggestion
            test::<p::micropascal, t::second, dv::micropascal_second>();
```

2022-08-15 19:14 UTC, iliekturtles commented on src/si/dynamic_viscosity.rs
> +            test::<p::pound_force_per_square_inch,  t::second,
```suggestion
            test::<p::pound_force_per_square_inch, t::second,
```

2022-08-15 19:14 UTC, iliekturtles commented on src/si/dynamic_viscosity.rs
> +            test::< m::slug, l::foot, t::second, dv::slug_per_foot_second>();
```suggestion
            test::<m::pound, l::foot, t::hour, dv::pound_per_foot_hour>();
            test::<m::gram, l::centimeter, t::second, dv::gram_per_centimeter_second>();
            test::<m::slug, l::foot, t::second, dv::slug_per_foot_second>();
```

2022-08-15 19:14 UTC, iliekturtles commented on src/si/dynamic_viscosity.rs
> +            fn test<M: m::Conversion<V>, L: l::Conversion<V>, T: t::Conversion<V>, DV: dv::Conversion<V>>()
```suggestion
            fn test<M: m::Conversion<V>, L: l::Conversion<V>, T: t::Conversion<V>,
                DV: dv::Conversion<V>>()
```

2022-08-15 20:12 UTC, crystal-growth commented
Thank you! 
Rebased and squashed into one commit.

2022-08-15 20:16 UTC, merged

2022-08-15 20:16 UTC, iliekturtles commented
Thanks so much for this PR!