Add atomic units of energy, mass, length, electric charge and current.
iliekturtles/uom pull request #324
Opened 2022-08-03 12:27 UTC by crystal-growth

Adding 

- Dalton (unified atomic mass unit = 1/12 * (mass of C12))
- Hartree (atomic unit of energy, ~27.2 eV)
- atomic unit of length (Bohr radius, 5.291 772 109 03 x 10-11 m )
- atomic unit of charge (absolute charge of electron, 1.602_176_634 x 10^-19 C)

2022-08-12 01:03 UTC, iliekturtles reviewed
I didn't get very far in this review. Comments about using "elementary charge" which seems more common than "atomic units"? Especially since the 2019 redefinition which uses "elementary charge" to define the ampere.

I included a possible change that has both elementary charge and atomic unit of charge.

2022-08-12 01:03 UTC, iliekturtles commented on src/si/electric_charge.rs
> +            "atomic unit of charge", "atomic units of charge";
```suggestion
        /// Electric charge carried by a single proton.
        @elementary_charge: 1.602_176_634_E-19; "e", "elementary charge", "elementary charges";
        @atomic_unit_of_charge: 1.602_176_634_E-19; "a.u. of charge", "atomic unit of charge",
            "atomic units of charge";
        @abcoulomb: 1.0_E1; "abC", "abcoulomb", "abcoulombs";
```

2022-08-12 06:46 UTC, crystal-growth commented
Thanks, completely agree with elementary charge!
Squashed and rebased.

2022-08-17 00:42 UTC, iliekturtles requested changes
Couple more questions about some of the constants that seem to be used as units. Otherwise close to merging!

2022-08-17 00:42 UTC, iliekturtles commented on src/si/electric_charge.rs
> +
Github won't let me use the full context for the changes, so I had to paste a diff below.

Put the elementary charge and atomic unit of charge tests in the same order as the unit definitions. For elementary charge possibly use elementary charge per second (see electric current review) or fallback to atomic unit of charge per second.

```diff
diff --git a/src/si/electric_charge.rs b/src/si/electric_charge.rs
index c749ec6..ea7406b 100644
--- a/src/si/electric_charge.rs
+++ b/src/si/electric_charge.rs
@@ -98,12 +98,12 @@ mod tests {
             test::<i::zeptoampere, t::second, q::zeptocoulomb>();
             test::<i::yoctoampere, t::second, q::yoctocoulomb>();
 
+            test::<i::elementary_charge_per_second, t::second, q::elementary_charge>();
+            test::<i::atomic_unit_of_charge_per_second, t::second, q::atomic_unit_of_charge>();
             test::<i::ampere, t::hour, q::ampere_hour>();
             test::<i::abampere, t::second, q::abcoulomb>();
             test::<i::statampere, t::second, q::statcoulomb>();
 
-            test::<i::atomic_unit_of_charge_per_second, t::second, q::atomic_unit_of_charge>();
-
             fn test<I: i::Conversion<V>, T: t::Conversion<V>, Q: q::Conversion<V>>() {
                 Test::assert_approx_eq(&ElectricCharge::new::<Q>(V::one()),
                     &(ElectricCurrent::new::<I>(V::one()) * Time::new::<T>(V::one())));
```

2022-08-17 00:42 UTC, iliekturtles commented on src/si/electric_current.rs
> +            "atomic unit of charge per second", "atomic units of charge per second";
Should elementary charge per second exist? If so, should probably add a comment.

```suggestion
        /// ...
        @elementary_charge_per_second: 1.602_176_634_E-19; "e/s", "elementary charge per second",
            "elementary charges per second";
        @atomic_unit_of_charge_per_second: 1.602_176_634_E-19; "a.u. of charge/s",
            "atomic unit of charge per second", "atomic units of charge per second";
        @abampere: 1.0_E1; "abA", "abampere", "abamperes";
```

2022-08-17 00:42 UTC, iliekturtles commented on src/si/energy.rs
> +        @hartree: 4.359_744_722_2071_E-18; "Ha", "hartree", "hartrees";
`Eₕ` seems more common than `Ha`. Thoughts?

```suggestion
        /// Atomic unit of energy (Hartree energy).
        @hartree: 4.359_744_722_207_1_E-18; "Eₕ", "hartree", "hartrees";
```

2022-08-17 00:42 UTC, iliekturtles commented on src/si/length.rs
> +        @atomic_unit_of_length: 5.291_772_109_03_E-11; "a.u. of length", "atomic unit of length", "atomic units of length";
Is Bohr radius actually used as a unit?

```suggestion
        @bohr_radius: 5.291_772_109_03_E-11; "a₀", "bohr radius", "bohr radiuses";
        /// Atomic unit of length (Bohr radius).
        @atomic_unit_of_length: 5.291_772_109_03_E-11; "a.u. of length", "atomic unit of length",
            "atomic units of length";
```

2022-08-17 00:42 UTC, iliekturtles commented on src/si/mass.rs
> +        @dalton: 1.660_539_066_60_E-27; "Da", "dalton", "daltons"; // Atomic mass unit
```suggestion
        @carat: 2.0_E-4; "ct", "carat", "carats";
        /// Unified atomic mass unit.
        @dalton: 1.660_539_066_60_E-27; "Da", "dalton", "daltons";
```

2022-08-17 08:52 UTC, crystal-growth commented
Thanks a lot for these suggestions!

1) Added elementary charge per second. It definitely should exist.
2) Agree with Eₕ, it's more common, and better stresses that it is Energy
3) I'm not sure if Bohr radius is an "official" unit, but it is very convenient to use it for describing hydrogen-like states in semiconductor physics:
`
let bohr_radius_of_shallow_donor_in_silicon = Length::new::<bohr_radius>(some_nondimentional_scaling_factor);
`
so I fully agree with adding it together with a.u. of length.

2022-08-23 18:16 UTC, iliekturtles commented on src/si/electric_current.rs
> +        /// Atomic unit of charge (electric charge carried by a single proton) per second
```suggestion
        /// Atomic unit of charge (electric charge carried by a single proton) per second.
```

2022-08-23 18:45 UTC, merged

2022-08-23 18:45 UTC, iliekturtles commented
Thanks so much for this PR! I just returned from vacation and will get back to working on the rest of your PRs.

2022-08-23 19:15 UTC, crystal-growth commented
Thank you very much! I apologize for this heap of PRs, and hope it will help improving usability of this great library. 

Starting using uom, I found it extremely useful in protecting me from various errors, including using wrong dimension for a given quantity. 
However, if a needed quantity is missing -- it becomes much less ergonomic. 

Now I'm "dimensionalizing" all my computational scripts, adding PRs for the quantities and units that are missing.
It's a great pleasure to get rid of functions with signatures like:
`some_func(atom_radius_in_picometers: f64 , atom_mass_in_amu: f64) -> diffusion_coeffient_in_cm2_s:f64`